language: dart
sudo: required
addons:
  postgresql: "9.6"
services:
  - postgresql
before_script:
  - psql -c 'create database open_campus;' -U postgres
  - psql -c 'create user open_campus with createdb;' -U postgres
  - psql -c "alter user open_campus with password '0p3n_c4mpu5&*';" -U postgres
  - psql -c 'grant all on database open_campus to open_campus;' -U postgres
  - pub get
script: pub run test -j 1 -r expanded
branches:
  only:
    - master
